"use client";

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
  Image,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", backgroundColor: "#ffffff" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomWidth: 2,
    borderBottomColor: "#f1f5f9",
    paddingBottom: 20,
    marginBottom: 30,
  },
  logoSection: { flexDirection: "row", alignItems: "center", gap: 10 },
  logo: { width: 30, height: 30, backgroundColor: "#2563eb", borderRadius: 6 },
  brand: {
    fontSize: 18,
    fontWeight: 900,
    color: "#0f172a",
    letterSpacing: -0.5,
  },
  titleSection: { textAlign: "right" },
  reportTitle: {
    fontSize: 24,
    fontWeight: 900,
    color: "#0f172a",
    letterSpacing: -0.5,
  },
  timestamp: {
    fontSize: 10,
    color: "#94a3b8",
    marginTop: 4,
    fontWeight: 700,
    textTransform: "uppercase",
  },

  summarySection: {
    marginBottom: 30,
    padding: 20,
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    border: "1px solid #e2e8f0",
  },
  summaryTitle: {
    fontSize: 10,
    fontWeight: 900,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
  },
  summaryText: {
    fontSize: 12,
    color: "#334155",
    lineHeight: 1.5,
    fontWeight: 400,
  },

  table: { width: "100%", marginTop: 10 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#0f172a",
    borderRadius: 6,
    marginBottom: 4,
  },
  tableHeaderCell: {
    padding: 12,
    fontSize: 9,
    fontWeight: 900,
    color: "#ffffff",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    minHeight: 40,
    alignItems: "center",
  },
  tableCell: { padding: 12, fontSize: 10, color: "#334155", fontWeight: 400 },

  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    color: "#cbd5e1",
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
    paddingTop: 10,
    fontWeight: 700,
    textTransform: "uppercase",
  },
});

interface ReportPDFProps {
  title: string;
  subtitle: string;
  data: any[];
  columns: { header: string; key: string }[];
}

export const ReportPDF = ({
  title,
  subtitle,
  data,
  columns,
}: ReportPDFProps) => {
  const timestamp = new Date().toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.logoSection}>
            <View style={styles.logo} />
            <Text style={styles.brand}>MIZIGO</Text>
          </View>
          <View style={styles.titleSection}>
            <Text style={styles.reportTitle}>{title.toUpperCase()}</Text>
            <Text style={styles.timestamp}>{timestamp}</Text>
          </View>
        </View>

        {/* Summary */}
        <View style={styles.summarySection}>
          <Text style={styles.summaryTitle}>Executive Summary</Text>
          <Text style={styles.summaryText}>
            This document provides a comprehensive analysis of{" "}
            {subtitle.toLowerCase()}. A total of {data.length} records have been
            identified and processed within this reporting cycle. The following
            ledger details the strategic distribution and operational telemetry
            for the selected parameters.
          </Text>
        </View>

        {/* Table */}
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            {columns.map((col, idx) => (
              <Text key={idx} style={[styles.tableHeaderCell, { flex: 1 }]}>
                {col.header}
              </Text>
            ))}
          </View>

          {data.map((row, rowIdx) => (
            <View key={rowIdx} style={styles.tableRow}>
              {columns.map((col, colIdx) => (
                <Text key={colIdx} style={[styles.tableCell, { flex: 1 }]}>
                  {row[col.key] || "N/A"}
                </Text>
              ))}
            </View>
          ))}
        </View>

        {/* Footer */}
        <Text style={styles.footer} fixed>
          Master Ledger • Generated by Mizigo Analytics Engine • Strictly
          Confidential
        </Text>
      </Page>
    </Document>
  );
};
